<a href="https://colab.research.google.com/github/sp-au-mu-nl/MediaDataProgramming/blob/main/intro_numpy/answer/intro_numpy_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ベクトルに対する配列演算の実行

In [23]:
import numpy as np

data = np.array([[3, 0.53, 4.0753, 0.5],
              [18, 1.78, 6.6678, 2.1328],
              [19, 0.86, 1.5177, 3.6852],
              [20, 1.6, 3.6375, 8.5389],
              [21, 3, 4.7243, 10.157],
              [23, 6.11, 9.0698, 2.8739],
              [38, 2.54, 5.3002, 4.4508]])

density = np.copy(data[:,1])
v1 = np.copy(data[:,2])
v2 = np.copy(data[:,3])

numpy は、ベクトルや行列を数学での数式と同じように扱えるように設計されています。例えば、1 つの配列の全ての要素にスカラー値を加算できます。
```
y = x + 2
```
v1 の各要素に 1 を加算して、結果を r という変数に保存しましょう。

In [24]:
r = v1 + 1
r

array([ 5.0753,  7.6678,  2.5177,  4.6375,  5.7243, 10.0698,  6.3002])

同じ shape を持つ任意の 2 つの配列を加算できます。
```
z = x + y
```
ベクトル v1 と v2 の和であるベクトル vs を作成しましょう。

In [25]:
vs = v1 + v2
vs

array([ 4.5753,  8.8006,  5.2029, 12.1764, 14.8813, 11.9437,  9.751 ])

配列の全ての要素をスカラーで乗算または除算できます。
```
z = 2*x
y = x/3
```
vs を 2 で除算した値 (平均) を含む変数 va を作成しましょう。

In [26]:
va = vs/2
va

array([2.28765, 4.4003 , 2.60145, 6.0882 , 7.44065, 5.97185, 4.8755 ])

numpy では、ベクトルに基本的な統計関数を適用して単一の出力を得られます。ベクトルの最大値は関数 max を使用して特定します。
```
xMax = np.max(x)
```
va ベクトルの最大値を含む変数 vm を作成しましょう。

In [27]:
vm = np.max(va)
vm

np.float64(7.44065)

numpy には、値のベクトルまたは配列全体に対し単一のコマンドで数学演算を実行する関数が用意されています。
```
xSqrt = np.sqrt(x)
```
関数 round を使用して、丸められた平均 va を含む vr という変数を作成しましょう。

In [28]:
vr = np.round(va)
vr

array([2., 4., 3., 6., 7., 6., 5.])

* 演算子を shape の等しいベクトルや行列に使用すると、要素単位の乗算(アダマール積) を求められます。

In [29]:
z = np.array([3,4]) * np.array([10,20])
z

array([30, 80])

これに対して、行列の乗算を計算したい場合には、@ 演算子を利用します。
例えば、2 つの shape が同じ 2 つのベクトルを @ で乗算すると、内積が求まります。

In [30]:
np.array([3,4]) @ np.array([10,20])

np.int64(110)

density と va の要素単位の積を含む mass という変数を作成しましょう。

In [31]:
mass = density * va
mass

array([ 1.2124545,  7.832534 ,  2.237247 ,  9.74112  , 22.32195  ,
       36.4880035, 12.38377  ])

以下の配列演算の例を示しました。


*   同じ shape の 2 つの配列
*   スカラーと配列

演算ができるサイズの組み合わせは他にもあります。例えば、以下を試してみましょう。

In [32]:
x = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]]) * np.array([[1],
               [2],
                [3],
                 [4]])

x の shape はどうなりましたか?

In [33]:
x

array([[ 1,  2],
       [ 6,  8],
       [15, 18],
       [28, 32]])

この動作の詳細については、numpy の broadcast という機構について調べてみてください。