<a href="https://colab.research.google.com/github/sp-au-mu-nl/MediaDataProgramming/blob/main/intro_numpy/answer/intro_numpy_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 複数の要素の抽出

In [1]:
import numpy as np

data = np.array([[3, 0.53, 4.0753, np.nan],
              [18, 1.78, 6.6678, 2.1328],
              [19, 0.86, 1.5177, 3.6852],
              [20, 1.6, 3.6375, 8.5389],
              [21, 3, 4.7243, 10.157],
              [23, 6.11, 9.0698, 2.8739],
              [38, 2.54, 5.3002, 4.4508]])

スライスでインデクスを指定できます。単独のコロン(:) は、その次元の全ての要素を指定します。
次の構文
```
y = A[1,:]
```
は、A の 2行目の全ての要素を含むベクトルを作成します。

data という行列の 2 列目を含む density という変数を作成しましょう。

In [2]:
density = data[:,1]
density

array([0.53, 1.78, 0.86, 1.6 , 3.  , 6.11, 2.54])

スライスでは、値の範囲できます。以下の構文は、行列 A の 1,2,3 行目を含む行列を作成します。
```
x = A[:3,:]
```
data の最後の2列を含む変数 volumes を作成しましょう。

In [3]:
volumes = data[:,-2:]
volumes

array([[ 4.0753,     nan],
       [ 6.6678,  2.1328],
       [ 1.5177,  3.6852],
       [ 3.6375,  8.5389],
       [ 4.7243, 10.157 ],
       [ 9.0698,  2.8739],
       [ 5.3002,  4.4508]])

単一のインデクスを使用して、ベクトル要素を参照できます。たとえば、
```
x = v[2]
```
は、v がベクトルの場合、v の 3 番目の要素を返します。

単一のインデクスを用いて、ベクトル density の 6 番目の要素を含む p という変数を作成しましょう。

In [4]:
p = density[5]
p

np.float64(6.11)

ベクトルの場合も、スライスでベクトル要素の一部を参照できます。たとえば、
```
x = v[2:]
```
は、3番目から最後までの要素を含む、ベクトル v の一部を返します。

スライスを使用して、density の 2番目から5番目までの要素を含む p というベクトルを作成しましょう。

In [5]:
p = density[1:5]
p

array([1.78, 0.86, 1.6 , 3.  ])

単一のインデクス値を使用して、ベクトルの要素を参照できます。たとえば、
```
x = v[2]
```
は、v がベクトル、もしくは列ベクトルの場合、ベクトル v の 3 番目の要素を返します。

行ベクトルの場合は、
```
x = v[0,2]
```
としなければなりません。

単一のインデクス値を使用して、ベクトル density の 6 番目の要素を含む p という変数を作成しましょう。


In [6]:
p = density[5]
p

np.float64(6.11)

インデクス値のスライスを使用して、ベクトル要素のサブセットを参照できます。例えば、
```
x = v[2:]
```
は、3番目から最後までの要素を含む、ベクトル v のサブセットを返します。

インデクス値のスライスを使用して、density の 2 番目から5番目までの要素を含む p というベクトルを作成しましょう。


In [7]:
p = density[1:5]
p

array([1.78, 0.86, 1.6 , 3.  ])

インデクスは、数値のリスト(配列)で指定しても構いません。density の 1,3,6 番目の値を抽出してみましょう。

In [8]:
density[[0,2,5]]

array([0.53, 0.86, 6.11])