<a href="https://colab.research.google.com/github/sp-au-mu-nl/MediaDataProgramming/blob/main/intro_numpy/answer/intro_numpy_19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 論理インデクスの作成

In [1]:
import numpy as np

data = np.array([[3, 0.53, 4.0753, 0.5],
              [18, 1.78, 6.6678, 2.1328], # ここまでの ipynb は 1 列目が間違っている
              [19, 0.86, 1.5177, 3.6852],
              [20, 1.6, 3.6375, 8.5389],
              [21, 3, 4.7243, 10.157],
              [23, 6.11, 9.0698, 2.8739],
              [38, 2.54, 5.3002, 4.4508]])

sample = np.copy(data[:,0])
v1 = np.copy(data[:,2])

 \>、<、==、~= などの関係演算子は、2 つの値の比較を行います。等しいか等しくないかの比較の結果は、True (1) または False (0) となります。

関係演算子 < を使用して、π が 4 より小さいかどうかをテストします。その出力を test という変数に代入します。

In [2]:
test = np.pi < 4
test

True

関係演算子を使用して、ベクトルまたは行列を単一のスカラー値と比較できます。結果は、元の配列と同じサイズの Boolean 配列となります。

In [3]:
np.array([5,10,15]) > 12

array([False, False,  True])

ベクトル v1 を、4 より小さい要素についてテストします。その出力を test という変数に代入します。

In [4]:
test = v1 < 4
test

array([False, False,  True,  True, False, False, False])

Boolean 配列を配列インデックスとして使用できます。その場合、numpy はインデックスが True である配列要素を抽出します。以下の例は、v1 内の 6 より大きい要素をすべて抽出します。

In [5]:
v = v1[v1 > 6]
v

array([6.6678, 9.0698])

v1 内の 4 より小さい要素をすべて含む変数 v を作成します。

In [6]:
v = v1[v1 < 4]
v

array([1.5177, 3.6375])

論理インデックスは、2 つの異なるベクトルと共に使用することもできます。

In [7]:
v = sample[v1 > 6]
v

array([18., 23.])

sample 内の要素のうち、v1 が 4 より小さいものを含む変数 s を作成します。

In [8]:
s = sample[v1 < 4]
s

array([19., 20.])

論理インデックスを使用して、値を配列に代入し直すことができます。たとえば、配列 x 内の 999 に等しい値をすべて値 1 に置き換える場合は、以下の構文を使用します。


> x[x==999] = 1

4 より小さい値がすべて値 0 に置き換わるように v1 を変更します。

In [9]:
v1[v1 < 4] = 0
v1

array([4.0753, 6.6678, 0.    , 0.    , 4.7243, 9.0698, 5.3002])

論理演算子 and (&) および or (|) を使用して、論理比較を組み合わせることができます。

4 より小さく、"かつ" 2 より大きい値を求めるには、& を次のように使用します。
> x = v1[(v1<4) & (v1>2)]

6 より大きい、"または" 2 より小さい値を求めるには、| を次のように使用します。
> x = v1[(v1>6) | (v1<2)]

sample 内にある、10 と 20 の間の値を取得してみてください。

In [10]:
sample[(sample>10) & (sample<20)]

array([18., 19.])