<a href="https://colab.research.google.com/github/sp-au-mu-nl/MediaDataProgramming/blob/main/intro_numpy/answer/intro_numpy_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 配列作成関数

In [13]:
import numpy as np

numpy には、乱数の行列など、一般に使用される行列の作成に役立つ関数が多数あります。

In [14]:
x = np.random.rand(2,2)
x

array([[0.41814714, 0.97575947],
       [0.67991448, 0.60698804]])

一様分布の乱数の 2行2列の行列が作成されました。

乱数の5行5列の行列である x という行列を作成しましょう。

In [15]:
x = np.random.rand(5,5)
x

array([[0.9515049 , 0.18816367, 0.25885128, 0.63703534, 0.74072159],
       [0.34870553, 0.67211558, 0.43661103, 0.34926975, 0.42523107],
       [0.28406896, 0.87145004, 0.4285624 , 0.10865886, 0.09484835],
       [0.52964023, 0.41828946, 0.30292757, 0.09834613, 0.48447273],
       [0.80285648, 0.88962639, 0.07441713, 0.47807857, 0.05933944]])

rand を利用して 5行1列の配列を作成して x という変数に代入しましょう。

In [16]:
x = np.random.rand(5,1)
x

array([[0.74412119],
       [0.63947579],
       [0.09978012],
       [0.66173602],
       [0.76745543]])

zeros を利用して 6 行 3 列の、すべてゼロの行列を作成して、x という変数に代入しましょう。

In [17]:
x = np.zeros((6,3),np.int32)
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

shape 属性を使うと、既存の行列と同じサイズの行列を簡単に作れます。

In [18]:
y = np.random.rand(*x.shape)
y.shape

(6, 3)

* は、タプルを数字の列に展開します。