<a href="https://colab.research.google.com/github/sp-au-mu-nl/MediaDataProgramming/blob/main/intro_numpy/notebook/intro_numpy_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 等間隔のベクトルの作成

In [ ]:
import numpy as np

以下のベクトルのように、等間隔の数値を含むベクトルを作成することはよくあります。

In [ ]:
y = np.array([5, 6, 7, 8])
y

array([5, 6, 7, 8])

値 1,2,3 をこの順序で含む x というベクトルを作成しましょう。

array([1, 2, 3])

長いベクトルの場合、数値を個々に入力することは現実的ではありません。等間隔のベクトルを作成するための簡潔な代替方法は、np.arange 関数を使用して開始点と「終了点の次の値」のみを指定することです。

In [ ]:
y = np.arange(5,9)
y

array([5, 6, 7, 8])

行ベクトルを作成するには、reshape メソッドを使うのが便利です。

In [ ]:
print(y.shape)
y = y.reshape(1,-1)
print(y.shape)
y

(4,)
(1, 4)


array([[5, 6, 7, 8]])

reshape は引数で、サイズを指定します。(x,y) で x 行 y 列の行列を生成します。-1 を指定すると自動で計算されます。

上記の y を列ベクトルにしてみましょう。

array([[5],
       [6],
       [7],
       [8]])

値 1,2,3,4 を含む x という行ベクトルを作成しましょう。

array([[1, 2, 3, 4]])

arange では、指定しないと間隔は 1 になりますが、以下のように間隔を指定できます。

In [ ]:
x = np.arange(20,26+1,2)
x

array([20, 22, 24, 26])

1 で始まり、5 で終わる、各要素の間隔が 0.5 の x という行ベクトルを作成しましょう。

array([[1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ]])

３で始まり、13 で終わる、各要素の間隔が 2 の x という行ベクトルを作成しましょう。

array([[ 3,  5,  7,  9, 11, 13]])

ベクトルに含める要素数がわかっていて、等間隔のベクトルを作成するときには、np.linspace を用います。

In [ ]:
x = np.linspace(0,1,5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

1 で始まり 10 で終わる、5 つの要素を含む x という行ベクトルを作成しましょう。

array([[ 1.  ,  3.25,  5.5 ,  7.75, 10.  ]])

行ベクトルから列ベクトルを作るときには、転置属性を用いることもできます。

In [ ]:
x = np.arange(1,4).reshape(1,-1)
x = x.T
x

array([[1],
       [2],
       [3]])

ベクトルは転置でも shape が変わらないことに留意してください。

In [ ]:
x = np.arange(1,4)
x.T

array([1, 2, 3])

単一のコマンドで、行ベクトルや列ベクトルを作成できます。

In [ ]:
 x = np.arange(1,5+2,2).reshape(1,-1)
 x

array([[1, 3, 5]])

単一のコマンドで 5 で始まり 9 で終わる、間隔 2 で配置された要素を持つ x という列ベクトルを作成しましょう。

array([[5],
       [7],
       [9]])

1 から $2\pi$ までの 100 個の要素を持つ等間隔ベクトルを作成してみましょう。

array([1.        , 1.05336551, 1.10673102, 1.16009652, 1.21346203,
       1.26682754, 1.32019305, 1.37355856, 1.42692407, 1.48028957,
       1.53365508, 1.58702059, 1.6403861 , 1.69375161, 1.74711711,
       1.80048262, 1.85384813, 1.90721364, 1.96057915, 2.01394465,
       2.06731016, 2.12067567, 2.17404118, 2.22740669, 2.2807722 ,
       2.3341377 , 2.38750321, 2.44086872, 2.49423423, 2.54759974,
       2.60096524, 2.65433075, 2.70769626, 2.76106177, 2.81442728,
       2.86779279, 2.92115829, 2.9745238 , 3.02788931, 3.08125482,
       3.13462033, 3.18798583, 3.24135134, 3.29471685, 3.34808236,
       3.40144787, 3.45481338, 3.50817888, 3.56154439, 3.6149099 ,
       3.66827541, 3.72164092, 3.77500642, 3.82837193, 3.88173744,
       3.93510295, 3.98846846, 4.04183396, 4.09519947, 4.14856498,
       4.20193049, 4.255296  , 4.30866151, 4.36202701, 4.41539252,
       4.46875803, 4.52212354, 4.57548905, 4.62885455, 4.68222006,
       4.73558557, 4.78895108, 4.84231659, 4.8956821 , 4.94904