<a href="https://colab.research.google.com/github/sp-au-mu-nl/MediaDataProgramming/blob/main/intro_numpy/notebook/intro_numpy_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 配列内の値の変更

In [ ]:
import numpy as np

data = np.array([[3, 0.53, 4.0753, np.nan],
              [18, 1.78, 6.6678, 2.1328],
              [19, 0.86, 1.5177, 3.6852],
              [20, 1.6, 3.6375, 8.5389],
              [21, 3, 4.7243, 10.157],
              [23, 6.11, 9.0698, 2.8739],
              [38, 2.54, 5.3002, 4.4508]])

コロン(:) を使用するとデータの列全体を抽出できます。

data の最後の 列を含む v2 という変数を作成しましょう。

array([    nan,  2.1328,  3.6852,  8.5389, 10.157 ,  2.8739,  4.4508])

変数の要素は、インデクス付けを代入と組み合わせて変更できます。
```
A[1] = 11
```
v2 の最初の要素を nan から 0.5 に変更しましょう。

array([ 0.5   ,  2.1328,  3.6852,  8.5389, 10.157 ,  2.8739,  4.4508])

python では、このとき v2 を代入して作成した元の data の要素の値も変わっていることに注意してください。

In [ ]:
data[:,-1]

array([ 0.5   ,  2.1328,  3.6852,  8.5389, 10.157 ,  2.8739,  4.4508])

元の値を変えたくないときは、copy 関数を使わなければなりません。

In [ ]:
v3 = np.copy(data[:,-1])
print(v3[0])
v3[0] = 1
print(v3[0])
data[0,-1]

0.5
1.0


np.float64(0.5)

data の最終行の最終列の要素の値を 5 に変更しましょう。

array([[ 3.    ,  0.53  ,  4.0753,  0.5   ],
       [18.    ,  1.78  ,  6.6678,  2.1328],
       [19.    ,  0.86  ,  1.5177,  3.6852],
       [20.    ,  1.6   ,  3.6375,  8.5389],
       [21.    ,  3.    ,  4.7243, 10.157 ],
       [23.    ,  6.11  ,  9.0698,  2.8739],
       [38.    ,  2.54  ,  5.3002,  5.    ]])

インデクス付けと代入を組み合わせると、配列の値を他の要素と等しくなるように変更できます。たとえば、次のコードは x[0] の値を x[1] に変更します。

```
x[0] = x[1]
```
data の 1 列目を data の 2列目の値に変更してみましょう。

array([[ 0.53  ,  0.53  ,  4.0753,  0.5   ],
       [ 1.78  ,  1.78  ,  6.6678,  2.1328],
       [ 0.86  ,  0.86  ,  1.5177,  3.6852],
       [ 1.6   ,  1.6   ,  3.6375,  8.5389],
       [ 3.    ,  3.    ,  4.7243, 10.157 ],
       [ 6.11  ,  6.11  ,  9.0698,  2.8739],
       [ 2.54  ,  2.54  ,  5.3002,  5.    ]])