<a href="https://colab.research.google.com/github/sp-au-mu-nl/MediaDataProgramming/blob/main/intro_numpy/notebook/intro_numpy_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 配列の手動入力

単一の数値はスカラーと呼ばれます。
4 の値をもつ x という変数を作成しましょう。

In [ ]:
x = 4

In [ ]:
import numpy as np

np.array を使うと、複数の要素を持つ配列(ベクトル)を作成できます。



In [ ]:
x = np.array([3,5])
x

array([3, 5])

7, 9 の二つの値を持つ x という配列を作成しましょう。

numpy で行ベクトルを作るときには、次のようにしましょう。

In [ ]:
x = np.array([[7,9]])
x

array([[7, 9]])

shape という属性を見ると、どのようなベクトルなのかわかります。

In [ ]:
x.shape

(1, 2)

1行2列の行ベクトルだとわかります。

一組の [] で行を表現し、行を , でつなぐと列ベクトルを表現できます。

In [ ]:
x = np.array([[1],[3]])
x

array([[1],
       [3]])

単一の列に 7 と 9 の 2 つの要素を持つ、x という配列を作成しましょう。

3, 10, 5 をこの順序で含む x という行ベクトルを作成しましょう。

array([[ 3, 10,  5]])

8,2,-4 をこの順序で含む x という列ベクトルを作成しましょう。

複数の列を持つ行を , で結合すると、複数の行と列をもつ配列である行列を作成できます。行は全て同じ列の数にしないといけません。

In [ ]:
x = np.array([[3,4,5],
 [6,7,8]])
x

array([[3, 4, 5],
       [6, 7, 8]])

次の値を持つ x という行列を作成しましょう
$$\begin{matrix}
5 & 6 & 7 \\
8 & 9 & 10 \\
\end{matrix}
$$

計算結果を使って、ベクトルや行列を作ることもできます。

In [ ]:
x = np.array([np.abs(-4), 4**2])
x

array([ 4, 16])

最初の要素として $\sqrt{10}$ を 2 番目の要素として $\pi^2$ を含む x というベクトルを作成しましょう。

array([3.16227766, 9.8696044 ])